version: 0.2
#Test


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 971422678605.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ecr-demo .
      - docker tag ecr-demo:latest 971422678605.dkr.ecr.us-west-2.amazonaws.com/ecr-demo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 971422678605.dkr.ecr.us-west-2.amazonaws.com/ecr-demo:latest
